### ISSUE TITLE
theme is missing from themes.gohugo.io

### ISSUE THREAD

**Issue by McShelby** [jpanther/lynx#101]
### What happened?

Currently the theme seems missing from the official themes page which is a pitty.

I've quickly checked and it is still in the `go.mod` file but still listed with a `v1.x.x` marker. Maybe the change in the major version number and some oddities in the theme sites build script is the culprit here.

https://github.com/gohugoio/hugoThemesSiteBuilder/blame/c70787143c50e14b56b0663e5647173604b9e8e6/cmd/hugothemesitebuilder/build/go.mod#L261

Edit: Well - yesterday was a little late. Your Lynx theme displays well - it was the Congo theme, that currently doesn't display.

**Comment by McShelby** [comment]
Updated my description.

**Comment by jpanther** [comment]
Thanks for noticing this, I had no idea! I've submitted a fix at https://github.com/gohugoio/hugoThemesSiteBuilder/pull/380
