### ISSUE TITLE
Ad block lists removing links/buttons

### ISSUE THREAD

**Issue by tarper24** [jpanther/lynx#45]
### What happened?

When using lists like [Fanboy's Social Blocking List](https://easylist.to/easylist/fanboy-social.txt) or [Fanboy's Annoyance List](https://easylist.to/easylist/fanboy-annoyance.txt), some buttons will be filtered out, such as Facebook, Instagram, Tumblr, Twitter, YouTube.

I made an attempt/example of fixing this over at https://github.com/tarper24/lynx/tree/fix/fanboy-blocks. I changed the css class names for the links to be base64 encoded in that fix and made a helper lookup function for Hugo to convert to that encoded form. I'm opening this issue to bring the conversation forward to explore less messy solutions.

## Expected

![image](https://user-images.githubusercontent.com/3270079/214770754-e4b031ad-dde2-4c17-8ed8-4cbdcad2c9da.png)

## Actual

![image](https://user-images.githubusercontent.com/3270079/214770760-f48436af-9bb9-4299-8bcd-f81696b22ee1.png)

### Theme version

v1.2.4

### Hugo version

v0.109.0+extended

### What browsers are you seeing the problem on?

Chrome

**Comment by jpanther** [comment]
Thanks for raising this issue, @tarper24. I do wonder if there is a neat way to avoid this problem, although it does beg the question about how much of an issue it really is. If people are blocking these items it's likely they're not using those networks to begin with, and so why would they ever click on the link in the first place?

At the end of the day people are choosing to block this and you can never completely predict every scenario that might come up on end user devices.

**Comment by tarper24** [comment]
I think I had started using them to remove the "Share to X" buttons and Facebook like counters. Sites like link tree have their own workarounds for it already.

I haven't been using those lists personally since creating this issue, and haven't really noticed anything annoying to me, so it's likely my internet landscape is different not and doesn't need that so much

**Comment by skhg** [comment]
I had the same problem. My LinkedIn button was hidden on iOS Safari by 1Blocker. The relevant rule is Hide Element `.link-linkedin` in the "Block Widgets" category.

I got around it by creating a custom link type `mynamecv` with the text `LinkedIn`, icon `linkedin` and a custom css rule to match the LinkedIn background colour. Works fine now.
