### ISSUE TITLE
what is "disableKinds"

### ISSUE THREAD

**Issue by JDChat** [jpanther/lynx#49]
### What happened?

In https://github.com/jpanther/lynx/blob/dev/exampleSite/config.toml

```toml
disableKinds = ["taxonomy", "term"]
```

Didn't know what it is for.

### Theme version

Latest

### Hugo version

v0.111 extended

### What browsers are you seeing the problem on?

Chrome

**Comment by jpanther** [comment]
This is a standard Hugo parameter and it simply disables page generation for these types as they are not really useful when making a simple links page. You can read more about it in the [Hugo docs](https://gohugo.io/getting-started/configuration/#disablekinds).

As this is not actually an issue, I'm going to close this request - questions can be asked using [Discussions](https://github.com/jpanther/lynx/discussions).
