### ISSUE TITLE
CSS not loading 

### ISSUE THREAD

**Issue by mansoorbarri** [jpanther/lynx#9]
### What happened?

I made the website using hugo and "rendered" it using ```hugo -D``` . I am hosting the site using github pages. CSS loads on live server and apache2 as well but it does not load with github pages. You can see the error @ https://mansoor.cf/socials and the github @ https://github.com/mansoorbarri/mansoor.github.io/tree/main/socials

### Theme version

1.1.0

### Hugo version

0.86.1

**Comment by mansoorbarri** [comment]
I am using Brave browser but the issue is there on firefox and chrome as well.

**Comment by Shubham56-droid** [comment]
You have put the wrong URL in the image then how will it be displayed

**Comment by Shubham56-droid** [comment]
change it to right URL your image is not main.png it main.webp that's why image is not visible

**Comment by Shubham56-droid** [comment]
Try to link CSS like : ./css/vncnt.css   use ' ./ '  in front of all files it may help

**Comment by mansoorbarri** [comment]
i used other theme now. Thanks for your help
